version: '3.8'

services:
  transmission:
    image: unixlinuxgeek/transmission
    network_mode: host
    restart: unless-stopped
    volumes:
      - <YOUR-SERVER-TRANSMISSION-DOWNLOADS-DIR-PATH>/transmission/downloads:/transmission/downloads
      
      # Example:
      # - /mnt/toshiba/transmission/downloads:/transmission/downloads


  minidlna:
    image: unixlinuxgeek/minidlna
    network_mode: host
    restart: unless-stopped
    volumes:
      # Replace <...>: 
      - <YOUR-SERVER-MINIDLNA-CONFIG-PATH>/minidlna.conf:/etc/minidlna.conf
      
      # Replace <...>:
      - <YOUR-SERVER-MOVIES-PATH>/transmission/downloads/movies:/transmission/downloads/movies
      
      # Replace <...>:
      - <YOUR-SERVER-TV_SERIES-PATH>/transmission/downloads/tv-series:/transmission/downloads/tv-seriies
      
      
      # Example:
      #- /mnt/toshiba/docker/minidlna/minidlna.conf:/etc/minidlna.conf  
      #- /mnt/toshiba/transmission/downloads/cartoons:/transmission/downloads/cartoons
      #- /mnt/toshiba/transmission/downloads/tv-series:/transmission/downloads/tv-series
      #- /mnt/toshiba/transmission/downloads/movies:/transmission/downloads/movies
      #- /mnt/toshiba/transmission/downloads/doc:/transmission/downloads/doc
      #- /mnt/toshiba/transmission/downloads/TOP-IMDB-MOVIES:/transmission/downloads/best
